# Generated by Django 2.2.1 on 2019-08-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='adress',
            new_name='address',
        ),
    ]
